#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l vmem=50gb
#PBS -l walltime=00:30:00

set -xe

BOLD=$(jq -r .bold config.json)
MASK=$(jq -r .mask config.json)
EVENTS=$(jq -r '.events // ""' config.json)
STIM=$(jq -r .stim config.json)

rm -Rf output
mkdir -p output

time singularity run -e \
    docker://anibalsolon/bl-app-popeye:latest \
    python main.py $BOLD $MASK $STIM config.json
